apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-app
  template:
    metadata:
      labels:
        app: next-app
    spec:
      containers:
      - name: next-app-container
        image: acr2dnd549.azurecr.io/next:v4
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 3000
        # resources:
        #   limits:
        #     cpu: "0.5"  
        #     memory: "512Mi"  
        #   requests:
        #     cpu: "0.25"  
        #     memory: "256Mi"
