apiVersion: apps/v1
kind: Deployment 
metadata:
  name: nginx-v1
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: nginx-v1 
  template:
    metadata:
      labels:
        app: nginx-v1 
    spec:
      containers:
      - name: nginx-v1
        image: nginx:1.25.2 
        ports:
        - name: http
          containerPort: 80
        resources:
          limits:
            cpu: "0.5"  
            memory: "512Mi"  
          requests:
            cpu: "0.25"  
            memory: "256Mi"
