apiVersion: v1
kind: Service
metadata:
  name: next-app-public
spec:
  type: LoadBalancer
  selector:
    app: next-app
  ports:
  - port: 80
    targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
  - port: 8080
    targetPort: 8080
