apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend-container
        image: acr2dnd549.azurecr.io/server:v1
        imagePullPolicy: IfNotPresent
        ports:
         - containerPort: 8080